name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/Unicorn.Umbraco.InvoiceManager/Unicorn.Umbraco.InvoiceManager.sln
    - name: Build
      run: dotnet build --no-restore src/Unicorn.Umbraco.InvoiceManager/Unicorn.Umbraco.InvoiceManager.sln
    - name: release package
      run: dotnet build src/InvoiceManager.sln --configuration Release /t:rebuild /t:pack -p:BuildTools=1 -p:PackageOutputPath=/releases/nuget
