name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
    DOTNET_NOLOGO: true
    DOTNET_GENERATE_ASPNET_CERTIFICATE: false
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    PROJECT: ./src/Unicorn.Umbraco.InvoiceManager/Unicorn.Umbraco.InvoiceManager.csproj
    OUTPUT: ./dist
jobs:
  build:

    runs-on:  windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.0'

    - name: Cache NuGet packages
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
            ${{ runner.os }}-nuget-
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ${{ env.PROJECT }} --no-restore ${{ env.PROJECT }}
    - name: release package
      run: dotnet build ${{ env.PROJECT }} --configuration Release /t:rebuild /t:pack -p:BuildTools=1 -p:PackageOutputPath=/releases/nuget
